title: Anjali Gondse # your name (or website title) here
logo: "/images/IMG_20220717_165713.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! Welcome to my Portfolio 
  <br><br>
  I am an Data Science Enthusiast 
  <br><br>
  <a href="www.linkedin.com/in/anjaligondse/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
 # your Google Analytics tracking ID here
